package city.modelo;
// Generated 22/07/2018 11:11:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivacionId generated by hbm2java
 */
@Embeddable
public class ActivacionId  implements java.io.Serializable {


     private int idActivacion;
     private int userId;

    public ActivacionId() {
    }

    public ActivacionId(int idActivacion, int userId) {
       this.idActivacion = idActivacion;
       this.userId = userId;
    }
   


    @Column(name="id_Activacion", nullable=false)
    public int getIdActivacion() {
        return this.idActivacion;
    }
    
    public void setIdActivacion(int idActivacion) {
        this.idActivacion = idActivacion;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActivacionId) ) return false;
		 ActivacionId castOther = ( ActivacionId ) other; 
         
		 return (this.getIdActivacion()==castOther.getIdActivacion())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdActivacion();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


