package city.modelo;
// Generated 22/07/2018 11:11:09 by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activacion generated by hbm2java
 */
@Entity
@Table(name="activacion"
    ,catalog="cityzen"
)
public class Activacion  implements java.io.Serializable {

    @Expose
     private ActivacionId id;
    
    
    //@Expose(serialize = false, deserialize = false) 
     private   Usuario usuario;
     
     @Expose
     private String tokenActivacion;
     
     @Expose
     private Date fechaCreacion;
     
     @Expose
     private Date fechaCaducidad;

    public Activacion() {
    }

	
    public Activacion(ActivacionId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Activacion(ActivacionId id, Usuario usuario, String tokenActivacion, Date fechaCreacion, Date fechaCaducidad) {
       this.id = id;
       this.usuario = usuario;
       this.tokenActivacion = tokenActivacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaCaducidad = fechaCaducidad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idActivacion", column=@Column(name="id_Activacion", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public ActivacionId getId() {
        return this.id;
    }
    
    public void setId(ActivacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="token_activacion", length=250)
    public String getTokenActivacion() {
        return this.tokenActivacion;
    }
    
    public void setTokenActivacion(String tokenActivacion) {
        this.tokenActivacion = tokenActivacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_caducidad", length=19)
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }




}


