package city.modelo;
// Generated 22/07/2018 11:11:09 by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name="categorias"
    ,catalog="cityzen"
)
public class Categorias  implements java.io.Serializable {

     @Expose
     private Integer idCategorias;
      @Expose
     private Date fechaCreacion;
       @Expose
     private Date fechaModificacion;
        @Expose
     private String nombreCategoria;
         @Expose
     private String descripcion;
     @Expose(serialize = false, deserialize = false)
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

    public Categorias() {
    }

    public Categorias(Date fechaCreacion, Date fechaModificacion, String nombreCategoria, String descripcion, Set<Incidencia> incidencias) {
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.nombreCategoria = nombreCategoria;
       this.descripcion = descripcion;
       this.incidencias = incidencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategorias", unique=true, nullable=false)
    public Integer getIdCategorias() {
        return this.idCategorias;
    }
    
    public void setIdCategorias(Integer idCategorias) {
        this.idCategorias = idCategorias;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    
    @Column(name="nombre_categoria", length=250)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    
    @Column(name="descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorias")
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }




}


