package city.modelo;
// Generated 22/07/2018 11:11:09 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name="log"
    ,catalog="cityzen"
)
public class Log  implements java.io.Serializable {


     private Integer idLog;
     private Date fecha;
     private String evento;
     private String detalle;
     private String ip;
     private String modeloDispositivo;

    public Log() {
    }

    public Log(Date fecha, String evento, String detalle, String ip, String modeloDispositivo) {
       this.fecha = fecha;
       this.evento = evento;
       this.detalle = detalle;
       this.ip = ip;
       this.modeloDispositivo = modeloDispositivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idLog", unique=true, nullable=false)
    public Integer getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(Integer idLog) {
        this.idLog = idLog;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="evento", length=250)
    public String getEvento() {
        return this.evento;
    }
    
    public void setEvento(String evento) {
        this.evento = evento;
    }

    
    @Column(name="detalle", length=65535)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="ip", length=50)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="modelo_dispositivo", length=300)
    public String getModeloDispositivo() {
        return this.modeloDispositivo;
    }
    
    public void setModeloDispositivo(String modeloDispositivo) {
        this.modeloDispositivo = modeloDispositivo;
    }




}


