package city.modelo;
// Generated 22/07/2018 11:11:09 by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="cityzen"
)
public class Usuario  implements java.io.Serializable {


    @Expose
     private Integer idUser;
    
    @Expose
     private Date fechaCreacion;
    
    @Expose
     private Date fechaModificacion;
    
    @Expose
     private String identificacion;
    
    @Expose
     private String nombres;
    
    @Expose
     private String apellidos;
    
    @Expose
     private Date fechaNacimiento;
    
    @Expose
     private String sexo;
    
    @Expose
     private String mail;
    
    @Expose
     private String clave;
    
    @Expose
     private String usuarioActivo;
    
   
     private Set<Activacion> activacions = new HashSet<Activacion>(0);
    
    
     private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

    public Usuario() {
    }

    public Usuario(Date fechaCreacion, Date fechaModificacion, String identificacion, String nombres, String apellidos, Date fechaNacimiento, String sexo, String mail, String clave, String usuarioActivo, Set<Activacion> activacions, Set<Incidencia> incidencias) {
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.mail = mail;
       this.clave = clave;
       this.usuarioActivo = usuarioActivo;
       this.activacions = activacions;
       this.incidencias = incidencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_user", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    
    @Column(name="identificacion", length=100)
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="nombres", length=250)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=250)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_Nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="sexo", length=2)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="mail", length=250)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="clave", length=100)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="usuario_activo", length=2)
    public String getUsuarioActivo() {
        return this.usuarioActivo;
    }
    
    public void setUsuarioActivo(String usuarioActivo) {
        this.usuarioActivo = usuarioActivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Activacion> getActivacions() {
        return this.activacions;
    }
    
    public void setActivacions(Set<Activacion> activacions) {
        this.activacions = activacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Incidencia> getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set<Incidencia> incidencias) {
        this.incidencias = incidencias;
    }




}


